package kr.co.crevill.voucher;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter @Setter @ToString
public class VoucherVo {
	private String voucherNo;
	private String grade;
	private String ticketName;
	private String price;
	private String salePrice;
	private String useTime;
	private String endDate;
	private String regId;
	private String regDate;
	private String updId;
	private String updDate;
	private String attribute;
	private String imageIdx;
	private String status;
	private String voucherTimeLeftHour;
	private String storeId;
	private String storeName;
	private String name;
	private String childName;
	private String playName;
	private String useTutoringTime;
	private String reservationId;
	private String cellPhone;
	private String timeLeftHour;
    private String timeLeftMinute;
    private String voucherUseId;
    private String storeNameShort; 
    private String isValid;
    private String saleStore;
    private String productNo;
    private String expireMonth;
    private String viewUseTime;
    private String viewEndDate;
    private String saleDate;
    private String regStore;
    private String promotion;
    private String cancelDate;
    private String promotionName;
    private String rStatus;
    private String diffDate;
	private String totalTime;
	private String usePeopleCount;
	private String refundCancelCount;
	private String totalUseTime;
	private String totalTimeLeft;
	private String usePer;
	private String voucherMemberCount;
	private String nonMemberCount;
	private String shortVoucherMemberCount;
	private String totalMemberCount;
	private String reservationAvaiableCount;
    private String reservationCount;
    private String noshowCount;
    private String entranceCount;
    private int sortOrder;
    private String refundDate;
    private String staffName;
    private String memo;
}
